// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: chat.proto

#include "chat.pb.h"
#include "chat.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace demo {

static const char* Broadcast_method_names[] = {
  "/demo.Broadcast/Subscribe",
};

std::unique_ptr< Broadcast::Stub> Broadcast::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Broadcast::Stub> stub(new Broadcast::Stub(channel));
  return stub;
}

Broadcast::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Subscribe_(Broadcast_method_names[0], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::demo::ServerMessage>* Broadcast::Stub::SubscribeRaw(::grpc::ClientContext* context, const ::demo::SubscribeRequest& request) {
  return ::grpc_impl::internal::ClientReaderFactory< ::demo::ServerMessage>::Create(channel_.get(), rpcmethod_Subscribe_, context, request);
}

void Broadcast::Stub::experimental_async::Subscribe(::grpc::ClientContext* context, ::demo::SubscribeRequest* request, ::grpc::experimental::ClientReadReactor< ::demo::ServerMessage>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderFactory< ::demo::ServerMessage>::Create(stub_->channel_.get(), stub_->rpcmethod_Subscribe_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::demo::ServerMessage>* Broadcast::Stub::AsyncSubscribeRaw(::grpc::ClientContext* context, const ::demo::SubscribeRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::demo::ServerMessage>::Create(channel_.get(), cq, rpcmethod_Subscribe_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::demo::ServerMessage>* Broadcast::Stub::PrepareAsyncSubscribeRaw(::grpc::ClientContext* context, const ::demo::SubscribeRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::demo::ServerMessage>::Create(channel_.get(), cq, rpcmethod_Subscribe_, context, request, false, nullptr);
}

Broadcast::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Broadcast_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< Broadcast::Service, ::demo::SubscribeRequest, ::demo::ServerMessage>(
          [](Broadcast::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::demo::SubscribeRequest* req,
             ::grpc_impl::ServerWriter<::demo::ServerMessage>* writer) {
               return service->Subscribe(ctx, req, writer);
             }, this)));
}

Broadcast::Service::~Service() {
}

::grpc::Status Broadcast::Service::Subscribe(::grpc::ServerContext* context, const ::demo::SubscribeRequest* request, ::grpc::ServerWriter< ::demo::ServerMessage>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace demo

